-- Run this once in the Supabase SQL Editor before starting the API.
create extension if not exists pgcrypto;
create type public.transport_mode as enum ('walk','bike','transit','drive');
create type public.price_basis as enum ('per_person','per_group','flat');
create type public.outing_status as enum ('active','completed','abandoned');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.places (id uuid primary key default gen_random_uuid(), name text not null, service_area text not null default 'indiranagar', category text not null, subcategory text, address text not null, description text not null, lat real not null, lng real not null, price_min integer not null, price_max integer not null, price_basis public.price_basis not null default 'per_person', opening_hours text not null, typical_visit_duration integer not null, suitable_for text[] not null default '{}', activities text[] not null default '{}', vibe text not null default '', rating real not null default 0, review_count integer not null default 0, experience_score real not null default .5, website_url text, maps_url text, source text not null default 'manual', verification_status text not null default 'unverified', last_verified text not null, confidence real not null default .5, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, subtitle text, vibe text, total_minutes integer not null, price_per_person integer not null, group_total integer not null, total_distance_km real not null default 0, travel_minutes integer not null default 0, feasible boolean not null, feasibility_note text, recommendation_label text not null, recommendation_reason text[] not null default '{}', request jsonb not null, route_geometry jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.plan_stops (id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.plans(id) on delete cascade, place_id uuid not null references public.places(id), position integer not null, arrival text, duration_minutes integer not null, travel_minutes integer not null default 0, distance_km real not null default 0, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.outings (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, plan_id uuid not null references public.plans(id) on delete cascade, status public.outing_status not null default 'active', current_stop_id uuid references public.plan_stops(id), started_at timestamptz not null default now(), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.outing_events (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, outing_id uuid references public.outings(id) on delete cascade, plan_id uuid references public.plans(id) on delete cascade, event_type text not null, payload jsonb not null default '{}', created_at timestamptz not null default now());
create index places_area_idx on public.places(service_area); create index places_category_idx on public.places(category); create index plans_user_idx on public.plans(user_id); create index plan_stops_plan_idx on public.plan_stops(plan_id); create index outings_user_idx on public.outings(user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id,email) values (new.id,new.email) on conflict (id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.places enable row level security; alter table public.plans enable row level security; alter table public.plan_stops enable row level security; alter table public.outings enable row level security; alter table public.outing_events enable row level security;
create policy "Public can read active places" on public.places for select using (active); create policy "Users manage own profile" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
-- The Express service-role client owns plan/outings writes. Do not expose its key to the browser.

insert into public.places (name,category,subcategory,address,description,lat,lng,price_min,price_max,opening_hours,typical_visit_duration,suitable_for,activities,vibe,rating,review_count,experience_score,source,last_verified,confidence) values
('Blue Tokai Coffee Roasters','Cafe','Coffee','12th Main Road, HAL 2nd Stage, Indiranagar','Specialty espresso and a sunny window seat.',12.9784,77.6408,150,300,'8:00 AM – 9:00 PM',35,'{solo,couple,friends}','{coffee,peaceful,photography}','Bright and unfussy',4.4,2100,.78,'manual-seed','2026-09-14',.7),
('ARAKU Coffee','Cafe','Specialty coffee','877, 12th Main Road, Indiranagar','Sit-down coffee and a full menu.',12.9788,77.6415,300,700,'9:00 AM – 11:00 PM',55,'{couple,friends}','{coffee,photography,peaceful}','Polished and photogenic',4.6,1500,.88,'manual-seed','2026-09-14',.65),
('Toit Brewpub','Dinner','Brewpub','298, 100 Feet Road, Indiranagar','Craft beer and comfort food.',12.9775,77.6404,400,900,'12:00 PM – 11:30 PM',75,'{friends,couple}','{food,drinks}','Lively and loud',4.5,8900,.85,'manual-seed','2026-09-14',.7),
('Corner House Ice Cream','Dessert','Ice cream','100 Feet Road, Indiranagar','Classic Bengaluru ice cream.',12.9776,77.6401,150,300,'11:00 AM – 11:30 PM',25,'{solo,couple,friends,family}','{food,chill}','Classic and cheerful',4.4,5200,.75,'manual-seed','2026-09-14',.75),
('Lahe Lahe','Culture','Art & poetry space','Indiranagar, Bengaluru','Community art, poetry and workshops.',12.9795,77.6385,200,500,'11:00 AM – 11:00 PM',60,'{solo,couple,friends}','{culture,peaceful,art}','Artsy and low-key',4.5,600,.75,'manual-seed','2026-09-14',.5),
('100 Feet Road Street Art Walk','Outdoor','Walk','100 Feet Road, Indiranagar','Free self-guided street-art walk.',12.979,77.64,0,0,'Always open',25,'{solo,couple,friends}','{outdoor,photography,peaceful,free}','Open-air and free',4.2,300,.6,'manual-seed','2026-09-14',.5);
