import { and, eq } from "drizzle-orm";
import { db, outingEvents, places, plans, planStops } from "@glimmr/db";
import { Router } from "express";
import { z } from "zod";
import { requireAuth, type AuthenticatedRequest } from "../middleware/auth.middleware";
import { km, recommend, type PlannerInput } from "../services/recommendation.service";
import { getRoute } from "../services/routing.service";
const router = Router();
const input = z.object({ from: z.string().min(1), to: z.string().min(1), availableMinutes: z.number().int().min(30).max(720), budget: z.number().int().min(0).max(100000), people: z.number().int().min(1).max(20), transport: z.enum(["walk","bike","transit","drive"]), outingType: z.string().min(1), preference: z.string().max(500).optional(), latitude: z.number().optional(), longitude: z.number().optional() });
const speed = { walk: 4.5, bike: 12, transit: 16, drive: 20 };
async function serialize(id: string, userId: string) { const [plan] = await db.select().from(plans).where(and(eq(plans.id,id),eq(plans.userId,userId))); if (!plan) return null; const rows = await db.select({ stop: planStops, place: places }).from(planStops).innerJoin(places,eq(planStops.placeId,places.id)).where(eq(planStops.planId,id)).orderBy(planStops.position); return { ...plan, steps: rows.map(({stop,place}) => ({ ...stop, place })) }; }
router.post("/plans/generate", requireAuth, async (req: AuthenticatedRequest,res) => { const parsed=input.safeParse(req.body); if(!parsed.success) return res.status(400).json({error:"Invalid planner request", details:parsed.error.flatten()}); const available=await db.select().from(places).where(eq(places.active,true)); const variants=recommend(parsed.data,available); const saved=[]; for(const variant of variants){ let distance=0, travelMinutes=0; const steps=variant.stops.map((place,i)=>{ const leg=i?km(variant.stops[i-1],place):0; const legMin=i?Math.max(3,Math.round(leg/speed[parsed.data.transport]*60)):0; distance+=leg;travelMinutes+=legMin;return {place,leg,legMin}; }); const total=steps.reduce((sum,x)=>sum+x.place.typicalVisitDuration+x.legMin,0); const [plan]=await db.insert(plans).values({userId:req.user!.id,title:variant.stops.map(x=>x.name).slice(0,2).join(" → "),subtitle:variant.stops.map(x=>x.subcategory??x.category).join(", "),vibe:variant.stops[0]?.vibe,totalMinutes:total,pricePerPerson:variant.stops.reduce((n,x)=>n+x.priceMax,0),groupTotal:variant.stops.reduce((n,x)=>n+x.priceMax,0)*parsed.data.people,totalDistanceKm:distance,travelMinutes,feasible:total<=parsed.data.availableMinutes,feasibilityNote:total>parsed.data.availableMinutes?"This plan is longer than your available time.":null,recommendationLabel:variant.label,recommendationReason:variant.reasons,request:parsed.data}).returning(); await db.insert(planStops).values(steps.map((x,i)=>({planId:plan.id,placeId:x.place.id,position:i,durationMinutes:x.place.typicalVisitDuration,travelMinutes:x.legMin,distanceKm:x.leg,arrival:i?"Next stop":"Start here"}))); saved.push(await serialize(plan.id,req.user!.id)); } await db.insert(outingEvents).values({userId:req.user!.id,eventType:"plan_generated",payload:{request:parsed.data, count:saved.length}}); res.status(201).json({plans:saved}); });
router.get("/plans/:id",requireAuth,async(req:AuthenticatedRequest,res)=>{const plan=await serialize(String(req.params.id),req.user!.id);if(!plan)return res.status(404).json({error:"Plan not found"});res.json(plan);});
router.patch("/plans/:id",requireAuth,async(req:AuthenticatedRequest,res)=>{const body=z.object({title:z.string().min(1).max(120).optional(),subtitle:z.string().max(240).nullable().optional()}).safeParse(req.body);if(!body.success)return res.status(400).json({error:"Invalid plan update"});const [plan]=await db.update(plans).set(body.data).where(and(eq(plans.id,String(req.params.id)),eq(plans.userId,req.user!.id))).returning();if(!plan)return res.status(404).json({error:"Plan not found"});res.json(await serialize(plan.id,req.user!.id));});
router.delete("/plans/:id/stops/:stopId",requireAuth,async(req:AuthenticatedRequest,res)=>{const plan=await serialize(String(req.params.id),req.user!.id);if(!plan)return res.status(404).json({error:"Plan not found"});if(plan.steps.length<2)return res.status(400).json({error:"A plan needs at least one stop"});await db.delete(planStops).where(and(eq(planStops.id,String(req.params.stopId)),eq(planStops.planId,plan.id)));res.json(await serialize(plan.id,req.user!.id));});
router.patch("/plans/:id/stops/:stopId",requireAuth,async(req:AuthenticatedRequest,res)=>{const body=z.object({durationMinutes:z.number().int().min(5).max(480).optional(),note:z.string().max(500).optional(),placeId:z.string().uuid().optional()}).safeParse(req.body);if(!body.success)return res.status(400).json({error:"Invalid stop update"});const plan=await serialize(String(req.params.id),req.user!.id);if(!plan)return res.status(404).json({error:"Plan not found"});await db.update(planStops).set(body.data).where(and(eq(planStops.id,String(req.params.stopId)),eq(planStops.planId,plan.id)));res.json(await serialize(plan.id,req.user!.id));});
export default router;
